<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * What a specific BOQ document produced the first time it was parsed.
 *
 * Looked up by content hash before any AI call, so re-uploading the same file
 * reuses the rows and questions it produced originally instead of asking the
 * model again — which would return something slightly different.
 */
class BoqParseResult extends Model
{
    protected $fillable = [
        'file_hash',
        'file_name',
        'file_size',
        'items',
        'questions',
        'hit_count',
        'last_used_at',
    ];

    protected $casts = [
        'items'        => 'array',
        'questions'    => 'array',
        'file_size'    => 'integer',
        'hit_count'    => 'integer',
        'last_used_at' => 'datetime',
    ];

    /**
     * Fetch a previous parse of this exact file.
     *
     * Records the hit so it is possible to tell later whether reuse is actually
     * happening, rather than assuming it is.
     */
    public static function forHash(string $hash): ?self
    {
        $result = static::where('file_hash', $hash)->first();

        if ($result) {
            $result->forceFill([
                'hit_count'    => $result->hit_count + 1,
                'last_used_at' => now(),
            ])->saveQuietly();
        }

        return $result;
    }

    /**
     * Store a parse so the next upload of this file can reuse it.
     *
     * Only complete parses are worth keeping: storing a partial one would pin
     * its missing rows in place for every future upload of the same document.
     *
     * @param  array<int, array<string, mixed>>  $items
     */
    public static function remember(
        string $hash,
        array $items,
        ?string $fileName = null,
        ?int $fileSize = null,
    ): void {
        if ($items === []) {
            return;
        }

        static::updateOrCreate(
            ['file_hash' => $hash],
            [
                'items'        => $items,
                'file_name'    => $fileName,
                'file_size'    => $fileSize,
                'last_used_at' => now(),
            ],
        );
    }

    /**
     * Attach the questions this file's rows produced.
     *
     * Separate from remember() because the questions are generated by a later
     * stage, after the rows have already been written.
     */
    public static function rememberQuestions(string $hash, array $questions): void
    {
        static::where('file_hash', $hash)->update(['questions' => $questions]);
    }
}
